#!/bin/bash

echo "🚀 Método Alternativo: Upload via cPanel/Painel de Controle"
echo ""
echo "Como a conexão SSH está bloqueada, use uma destas opções:"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo "OPÇÃO 1: cPanel File Manager (Mais Simples)"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "1. Acesse o painel cPanel da HosterGator/seu host:"
echo "   https://srv993737.hstgr.cloud:2083/ (ou similar)"
echo "   Login: seu usuário cPanel"
echo ""
echo "2. Vá em File Manager → /public_html"
echo ""
echo "3. Upload dos arquivos em dist/:"
echo "   - dist/index.html"
echo "   - dist/assets/ (pasta completa)"
echo ""
echo "4. Acesse: https://cafeeverso.fun"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo "OPÇÃO 2: FTP/SFTP (via cliente)"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "1. Use um cliente FTP (Filezilla, WinSCP, etc):"
echo "   Host: 72.60.147.56"
echo "   User: root"
echo "   Pass: (sua senha SSH)"
echo ""
echo "2. Conecte em SFTP (porta 22) ou FTP (porta 21)"
echo ""
echo "3. Navegue até /var/www/html ou /public_html"
echo ""
echo "4. Upload de dist/* para lá"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo "OPÇÃO 3: Desbloquear SSH"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "Contate o suporte da HosterGator:"
echo "   Solicite para desbloquear SSH na porta 22"
echo "   Mencione que precisa fazer deploy"
echo ""
echo "Depois execute novamente:"
echo "   export VPS_IP='72.60.147.56'"
echo "   export VPS_USER='root'"
echo "   ./deploy.sh"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "✅ Arquivos prontos em ./dist para upload manual"
echo ""

ls -lh dist/

