export const events = [
  {
    id: "evt-001",
    title: "Noite Café & Poesia",
    host: "Café Aurora",
    host_id: "est-001",
    city: "São Paulo",
    country: "BR",
    langs: ["PT", "EN"],
    verso_reward: 50,
    nft: true,
    mode: "Presencial",
    category: "Poesia",
    date: "2025-05-12T20:00:00-03:00",
    date_label: "12 mai · 20:00",
    participants: 84,
    capacity: 120,
    image_tone: "amber",
    description:
      "Uma noite imersiva de poesia contemporânea com leituras ao vivo, debate e uma xícara de espresso especial da casa. NFT de presença emitido ao final.",
  },
  {
    id: "evt-002",
    title: "Clube Global de Leitura",
    host: "Verso House",
    host_id: "est-002",
    city: "Online",
    country: null,
    langs: ["PT", "EN", "ES", "DE", "FR", "JA"],
    verso_reward: 40,
    nft: true,
    mode: "Online",
    category: "Clube de leitura",
    date: "2025-05-18T21:00:00-03:00",
    date_label: "18 mai · 21:00",
    participants: 312,
    capacity: 500,
    image_tone: "sky",
    description:
      "Sessão mensal do clube global com tradução em tempo real. Obra do mês: 'O Apanhador no Campo de Centeio'. Discussão em 6 idiomas simultâneos.",
  },
  {
    id: "evt-003",
    title: "Escrita Criativa Internacional",
    host: "Verso Studio",
    host_id: "est-003",
    city: "Online",
    country: null,
    langs: ["PT", "EN", "ES", "DE", "FR", "IT", "PL", "RU", "ZH", "JA", "AR", "KO"],
    verso_reward: 80,
    nft: true,
    mode: "Online",
    category: "Escrita",
    date: "2025-05-23T19:00:00-03:00",
    date_label: "23 mai · 19:00",
    participants: 178,
    capacity: 300,
    image_tone: "violet",
    description:
      "Workshop intensivo de escrita criativa com autores de 12 países. Exercícios, feedback e publicação colaborativa na plataforma.",
  },
  {
    id: "evt-004",
    title: "Café Filosófico",
    host: "Páginas & Espresso",
    host_id: "est-004",
    city: "Buenos Aires",
    country: "AR",
    langs: ["ES", "PT"],
    verso_reward: 35,
    nft: true,
    mode: "Híbrido",
    category: "Filosofia",
    date: "2025-05-29T19:30:00-03:00",
    date_label: "29 mai · 19:30",
    participants: 47,
    capacity: 80,
    image_tone: "emerald",
    description:
      "Debate filosófico sobre a frase de Borges: 'Uma biblioteca é uma espécie de máquina do tempo.' Presencial no espaço e via sala Café & Verso.",
  },
  {
    id: "evt-005",
    title: "Rota Cultural Livrarias",
    host: "Livraria Atlântica",
    host_id: "est-005",
    city: "Lisboa",
    country: "PT",
    langs: ["PT", "EN"],
    verso_reward: 120,
    nft: true,
    mode: "Presencial",
    category: "Livraria",
    date: "2025-06-04T18:00:00+01:00",
    date_label: "04 jun · 18:00",
    participants: 63,
    capacity: 100,
    image_tone: "rose",
    description:
      "Passeio guiado pelas livrarias independentes de Lisboa com curadoria especial, encontros com autores e NFT comemorativo da rota cultural.",
  },
  {
    id: "evt-006",
    title: "Berlin Reading Night",
    host: "Buchhandlung Verso",
    host_id: "est-006",
    city: "Berlin",
    country: "DE",
    langs: ["DE", "EN"],
    verso_reward: 90,
    nft: true,
    mode: "Presencial",
    category: "Clube de leitura",
    date: "2025-06-08T22:00:00+02:00",
    date_label: "08 jun · 22:00",
    participants: 55,
    capacity: 70,
    image_tone: "slate",
    description:
      "Noite de leitura silenciosa e coletiva no porão da Buchhandlung Verso, com trilha sonora instrumental ao vivo e café especial da casa.",
  },
  {
    id: "evt-007",
    title: "Tokyo Slow Reading",
    host: "Bunkitsu Annex",
    host_id: "est-007",
    city: "Tokyo",
    country: "JP",
    langs: ["JA", "EN"],
    verso_reward: 60,
    nft: true,
    mode: "Presencial",
    category: "Meditação & Leitura",
    date: "2025-06-14T14:00:00+09:00",
    date_label: "14 jun · 14:00",
    participants: 28,
    capacity: 40,
    image_tone: "amber",
    description:
      "Sessão de leitura lenta inspirada no conceito japonês de 'ma' — pausa, espaço e presença. Chá matcha e haiku compartilhado ao final.",
  },
  {
    id: "evt-008",
    title: "Verso Sessions NY",
    host: "The Reading Cup",
    host_id: "est-008",
    city: "New York",
    country: "US",
    langs: ["EN", "ES"],
    verso_reward: 70,
    nft: true,
    mode: "Híbrido",
    category: "Encontro cultural",
    date: "2025-06-21T20:00:00-04:00",
    date_label: "21 jun · 20:00",
    participants: 92,
    capacity: 150,
    image_tone: "indigo",
    description:
      "Encontro mensal da comunidade Café & Verso em Nova York com leituras bilíngues, painel de autores emergentes e degustação de cafés especiais.",
  },
];

export const establishments = [
  {
    id: "est-001",
    name: "Café Aurora",
    slug: "cafe-aurora",
    city: "São Paulo",
    country: "BR",
    type: "Café",
    plan: "Embaixador",
    plan_id: 3,
    status: "Ativo",
    verified: true,
    langs: ["PT", "EN"],
    verso_received: 4800,
    nfts_issued: 312,
    active_campaigns: 3,
    members_reached: 1240,
    wallet: "0x3f4...a2b1",
    rating: 4.9,
    reviews: 214,
    description:
      "Café especialidade no coração do Bixiga. Grãos de origem única, preparo artesanal e uma programação cultural permanente.",
    coordinates: { x: 30, y: 68 },
  },
  {
    id: "est-002",
    name: "Verso House",
    slug: "verso-house",
    city: "Online",
    country: null,
    type: "Espaço Cultural",
    plan: "Embaixador",
    plan_id: 3,
    status: "Ativo",
    verified: true,
    langs: ["PT", "EN", "ES", "DE", "FR"],
    verso_received: 9200,
    nfts_issued: 780,
    active_campaigns: 5,
    members_reached: 8400,
    wallet: "0x7a1...c8d4",
    rating: 4.8,
    reviews: 521,
    description:
      "Hub digital do ecossistema Café & Verso. Eventos, clubes de leitura, residências e produção cultural multilíngue em escala global.",
    coordinates: null,
  },
  {
    id: "est-003",
    name: "Livraria Atlântica",
    slug: "livraria-atlantica",
    city: "Lisboa",
    country: "PT",
    type: "Livraria",
    plan: "Comunidade",
    plan_id: 2,
    status: "Ativo",
    verified: true,
    langs: ["PT", "EN"],
    verso_received: 2100,
    nfts_issued: 142,
    active_campaigns: 2,
    members_reached: 680,
    wallet: "0x9c2...f1e7",
    rating: 4.7,
    reviews: 98,
    description:
      "Livraria independente em Lisboa com curadoria editorial contemporânea, eventos de lançamento e uma pequena galeria de artes visuais.",
    coordinates: { x: 46, y: 40 },
  },
  {
    id: "est-004",
    name: "Verso House Berlin",
    slug: "verso-house-berlin",
    city: "Berlin",
    country: "DE",
    type: "Espaço Cultural",
    plan: "Embaixador",
    plan_id: 3,
    status: "Ativo",
    verified: true,
    langs: ["DE", "EN"],
    verso_received: 6700,
    nfts_issued: 445,
    active_campaigns: 4,
    members_reached: 3200,
    wallet: "0x5b8...d9a3",
    rating: 4.8,
    reviews: 302,
    description:
      "Espaço cultural e café especialidade em Mitte, Berlin. Residências artísticas, clube internacional de leitura e eventos multilíngues semanais.",
    coordinates: { x: 53, y: 32 },
  },
  {
    id: "est-005",
    name: "The Reading Cup NY",
    slug: "the-reading-cup-ny",
    city: "New York",
    country: "US",
    type: "Café",
    plan: "Comunidade",
    plan_id: 2,
    status: "Ativo",
    verified: true,
    langs: ["EN", "ES"],
    verso_received: 3400,
    nfts_issued: 228,
    active_campaigns: 2,
    members_reached: 1900,
    wallet: "0x2d6...b0f5",
    rating: 4.6,
    reviews: 178,
    description:
      "Café literário no West Village. Coleção de 4.000 títulos, café de origem Brooklyn, eventos semanais e sala de leitura para sócios.",
    coordinates: { x: 25, y: 38 },
  },
  {
    id: "est-006",
    name: "Páginas & Espresso",
    slug: "paginas-espresso",
    city: "Buenos Aires",
    country: "AR",
    type: "Café",
    plan: "Essencial",
    plan_id: 1,
    status: "Ativo",
    verified: false,
    langs: ["ES", "PT"],
    verso_received: 820,
    nfts_issued: 54,
    active_campaigns: 1,
    members_reached: 320,
    wallet: "0x1a4...e3c2",
    rating: 4.5,
    reviews: 61,
    description:
      "Café de bairro com alma literária em Palermo, Buenos Aires. Espresso de torra média, bistrô compacto e roda de filosofia às quintas.",
    coordinates: { x: 31, y: 78 },
  },
  {
    id: "est-007",
    name: "Bunkitsu Annex",
    slug: "bunkitsu-annex",
    city: "Tokyo",
    country: "JP",
    type: "Livraria",
    plan: "Comunidade",
    plan_id: 2,
    status: "Ativo",
    verified: true,
    langs: ["JA", "EN"],
    verso_received: 1900,
    nfts_issued: 118,
    active_campaigns: 2,
    members_reached: 740,
    wallet: "0x8e3...a7d1",
    rating: 4.9,
    reviews: 143,
    description:
      "Livraria curada com entrada paga em Roppongi, Tokyo. Ambiente meditativo, chá e café de especialidade, e uma seleção editorial de alta curadoria.",
    coordinates: { x: 84, y: 42 },
  },
  {
    id: "est-008",
    name: "Biblioteca Viva Social",
    slug: "biblioteca-viva-social",
    city: "Fortaleza",
    country: "BR",
    type: "ONG",
    plan: "Café Aberto",
    plan_id: 0,
    status: "Ativo",
    verified: true,
    langs: ["PT"],
    verso_received: 280,
    nfts_issued: 22,
    active_campaigns: 0,
    members_reached: 150,
    wallet: "0x4f1...c6b9",
    rating: 5.0,
    reviews: 27,
    description:
      "Biblioteca comunitária e espaço de leitura para crianças e jovens em situação de vulnerabilidade social no bairro Bom Jardim.",
    coordinates: null,
  },
];

export const communities = [
  {
    id: "com-001",
    name: "Café & Poesia",
    category: "Poesia",
    langs: ["PT", "EN"],
    members: 2400,
    active_now: 38,
    events_this_month: 4,
    country_flags: ["BR", "PT", "US", "UK"],
    tone: "amber",
    description:
      "Clube de poesia contemporânea com sessões semanais de leitura, workshop de escrita e publicação colaborativa entre membros de 4 países.",
  },
  {
    id: "com-002",
    name: "Fantasia Global",
    category: "Ficção Científica & Fantasia",
    langs: ["EN", "ES", "DE"],
    members: 8100,
    active_now: 214,
    events_this_month: 8,
    country_flags: ["US", "DE", "MX", "AR", "UK"],
    tone: "violet",
    description:
      "Maior clube de fantasia da plataforma. Leituras simultâneas, debates épicos e uma maratona anual de 72 horas de imersão literária.",
  },
  {
    id: "com-003",
    name: "Filosofia à Meia-Noite",
    category: "Filosofia",
    langs: ["PT", "ES", "FR"],
    members: 1700,
    active_now: 22,
    events_this_month: 6,
    country_flags: ["BR", "FR", "AR", "PT"],
    tone: "slate",
    description:
      "Debates filosóficos noturnos ao redor de textos clássicos e contemporâneos. Sócrates encontra Bolaño às 23h.",
  },
  {
    id: "com-004",
    name: "Escrita Criativa Internacional",
    category: "Escrita",
    langs: ["PT", "EN", "ES", "DE", "IT", "FR"],
    members: 1200,
    active_now: 41,
    events_this_month: 5,
    country_flags: ["BR", "IT", "DE", "FR", "US"],
    tone: "rose",
    description:
      "Workshop permanente de escrita criativa com mentorias, publicações colaborativas e residências virtuais para autores emergentes.",
  },
  {
    id: "com-005",
    name: "Livrarias Independentes",
    category: "Curadoria",
    langs: ["PT", "EN", "ES", "DE", "JA"],
    members: 920,
    active_now: 15,
    events_this_month: 3,
    country_flags: ["PT", "JP", "DE", "UK", "BR"],
    tone: "emerald",
    description:
      "Rede de livrarias independentes e leitores que valorizam a curadoria editorial, o espaço físico e a experiência do livro como objeto.",
  },
  {
    id: "com-006",
    name: "Café Especial & Literatura",
    category: "Café & Livros",
    langs: ["PT", "EN"],
    members: 3300,
    active_now: 67,
    events_this_month: 7,
    country_flags: ["BR", "US", "PT", "CO", "ET"],
    tone: "amber",
    description:
      "Para quem não separa a leitura do ritual do café. Cupping, terroir sensorial e literatura como estilo de vida.",
  },
];

export const nfts = [
  {
    id: "nft-001",
    name: "Verso Passport",
    collection: "Genesis",
    edition: "Fundadores",
    description:
      "O NFT inaugural do ecossistema Café & Verso. Emitido apenas para os primeiros 500 membros que completaram o onboarding completo da plataforma.",
    total_supply: 500,
    issued: 312,
    tone: "amber",
    rarity: "Raro",
    perks: ["Acesso antecipado a eventos", "Badge fundador permanente", "Multiplier de $VERSO x1.5"],
  },
  {
    id: "nft-002",
    name: "Verso Moments",
    collection: "Moments",
    edition: "Colecionável",
    description:
      "Registro digital de momentos culturais únicos. Cada NFT captura um evento, uma leitura ou um encontro que moldou a história da plataforma.",
    total_supply: 2000,
    issued: 847,
    tone: "rose",
    rarity: "Incomum",
    perks: ["Memória digital permanente", "Compartilhamento na galeria global"],
  },
  {
    id: "nft-003",
    name: "Café Visit Badge",
    collection: "Presença",
    edition: "Recorrente",
    description:
      "Emitido a cada visita confirmada em um estabelecimento parceiro do Café & Verso. Acumule badges e desbloqueie recompensas culturais.",
    total_supply: null,
    issued: 4200,
    tone: "emerald",
    rarity: "Comum",
    perks: ["Verificação de visita", "Histórico de estabelecimentos visitados"],
  },
  {
    id: "nft-004",
    name: "Livraria Experience",
    collection: "Curadoria",
    edition: "Editorial",
    description:
      "NFT exclusivo para visitantes de livrarias parceiras. Cada badge mostra a curadoria do espaço e a experiência de descoberta literária.",
    total_supply: null,
    issued: 1850,
    tone: "sky",
    rarity: "Incomum",
    perks: ["Recomendações editoriais personalizadas", "+20 $VERSO por visita"],
  },
  {
    id: "nft-005",
    name: "Global Reading Room",
    collection: "Especial",
    edition: "Exclusivo",
    description:
      "Emitido apenas a participantes do Global Reading Room — encontro trimestral com autores internacionais e curadores de 5 continentes.",
    total_supply: 200,
    issued: 48,
    tone: "violet",
    rarity: "Épico",
    perks: ["Acesso permanente ao arquivo do evento", "Credencial de curador global", "Multiplier de $VERSO x2"],
  },
  {
    id: "nft-006",
    name: "Poesia & Espresso",
    collection: "Noite Café & Poesia",
    edition: "Edição Especial",
    description:
      "NFT comemorativo da primeira temporada da Noite Café & Poesia em São Paulo. Obra visual gerada a partir dos poemas lidos na noite inaugural.",
    total_supply: 120,
    issued: 84,
    tone: "rose",
    rarity: "Raro",
    perks: ["Acesso ao arquivo de poemas", "Desconto em eventos futuros do Café Aurora"],
  },
  {
    id: "nft-007",
    name: "Berlin Reading Night",
    collection: "Verso House Berlin",
    edition: "Anual",
    description:
      "Emitido aos participantes da Berlin Reading Night. Cada edição anual tem uma arte exclusiva inspirada na obra debatida na sessão.",
    total_supply: 70,
    issued: 55,
    tone: "slate",
    rarity: "Raro",
    perks: ["Badge de leitor Berlim", "Prioridade de inscrição no próximo evento"],
  },
  {
    id: "nft-008",
    name: "Verso Solidário",
    collection: "Impacto Social",
    edition: "Doação",
    description:
      "Emitido quando um usuário ou estabelecimento destina $VERSO a uma entidade filantrópica verificada. Registro imutável de impacto cultural.",
    total_supply: null,
    issued: 620,
    tone: "emerald",
    rarity: "Incomum",
    perks: ["Certificado digital de doação", "Badge de impacto no perfil"],
  },
];

export const mapPins = [
  { id: "pin-001", est_id: "est-001", city: "São Paulo", country: "BR", x: 30, y: 68, kind: "Café", plan: 3, verified: true },
  { id: "pin-002", est_id: "est-004", city: "Berlin", country: "DE", x: 53, y: 32, kind: "Livraria", plan: 3, verified: true },
  { id: "pin-003", est_id: "est-005", city: "New York", country: "US", x: 25, y: 38, kind: "Evento", plan: 2, verified: true },
  { id: "pin-004", est_id: "est-003", city: "Lisboa", country: "PT", x: 46, y: 40, kind: "Café", plan: 2, verified: true },
  { id: "pin-005", est_id: "est-007", city: "Tokyo", country: "JP", x: 84, y: 42, kind: "Comunidade", plan: 2, verified: true },
  { id: "pin-006", est_id: "est-006", city: "Buenos Aires", country: "AR", x: 31, y: 78, kind: "Livraria", plan: 1, verified: false },
  { id: "pin-007", city: "Paris", country: "FR", x: 49, y: 35, kind: "Café", plan: 1, verified: true, name: "Le Verso Parisien" },
];

export const stats = {
  users_active: 28400,
  users_growth_pct: 18.4,
  establishments_total: 342,
  events_scheduled: 47,
  nfts_issued: 9850,
  verso_distributed: 1240000,
  donations_total: 84,
  campaigns_pending: 12,
  reports_pending: 3,
  countries: 38,
  languages: 22,
};

export const recentActivity = [
  { type: "event_join", user: "Ana Martins", detail: "entrou no Clube Global de Leitura", timestamp: "há 2 min" },
  { type: "nft_issued", user: "Café Aurora", detail: "emitiu NFT para 12 participantes", timestamp: "há 8 min" },
  { type: "establishment_joined", user: "Livraria Minerva", detail: "solicitou cadastro — Plano Essencial", timestamp: "há 14 min" },
  { type: "donation", user: "Verso House Berlin", detail: "destinou 800 $VERSO à Biblioteca Viva Social", timestamp: "há 21 min" },
  { type: "campaign_approved", user: "The Reading Cup NY", detail: "campanha aprovada — Verso Sessions Junho", timestamp: "há 35 min" },
];

export const users = [
  {
    id: "usr-001",
    name: "Ana Martins",
    avatar_initials: "AM",
    lang_in: "PT",
    lang_out: "EN",
    level: "Leitor Global",
    verso_balance: 1240,
    nfts: 8,
    communities: 4,
    events_attended: 12,
    interests: ["Poesia", "Cafés especiais", "Filosofia", "Fantasia"],
    country: "BR",
    city: "São Paulo",
    member_since: "2024-03",
  },
];
